"""Extension stub code generator.

Generates ready-to-run Python source files for:
1. **Connector providers** — implement the ConnectorProviderProtocol to
   integrate an external service (e.g. Slack, Jira, custom API).
2. **Event handlers** — subscribe to EventBus events for custom
   side-effects (notifications, metrics, logging).
3. **Phase context hooks** — inject context data into a phase before
   agent execution (e.g. load previous results, external data).

All stubs are fully functional skeletons with real imports, logging,
type hints, and docstrings.  After generation, the user edits the
``TODO`` sections to add their domain logic.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

from studio.exceptions import ExtensionStubError
from studio.ir.models import TeamSpec
from studio.manifest.tracker import ManifestTracker

logger = logging.getLogger(__name__)


@dataclass
class ExtensionStubResult:
    """Result of generating extension stubs.

    Attributes:
        files: Mapping of relative path → generated source code.
        written: Absolute paths of files actually written to disk.
        skipped: Relative paths skipped due to user-ownership.
    """

    files: dict[str, str] = field(default_factory=dict)
    written: list[Path] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def _connector_stub(provider_id: str, display_name: str, capability: str) -> str:
    """Generate a connector provider stub."""
    class_name = "".join(part.capitalize() for part in provider_id.replace("-", "_").split("_"))
    return f'''"""Connector provider: {display_name}.

Auto-generated by Agent-Orchestrator Studio.
Edit the TODO sections to add your integration logic.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class {class_name}OperationDescriptor:
    """Describes one operation this provider supports."""

    operation: str
    description: str
    capability_type: str = "{capability}"
    read_only: bool = True
    required_parameters: list[str] = field(default_factory=list)
    optional_parameters: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class {class_name}Descriptor:
    """Provider descriptor returned by get_descriptor()."""

    provider_id: str = "{provider_id}"
    display_name: str = "{display_name}"
    capability_types: list[str] = field(default_factory=lambda: ["{capability}"])
    operations: list[{class_name}OperationDescriptor] = field(default_factory=list)
    enabled: bool = True
    auth_required: bool = False
    auth_type: str = "none"
    parameter_schemas: dict[str, Any] = field(default_factory=dict)


class {class_name}Provider:
    """Connector provider for {display_name}.

    Implements the ConnectorProviderProtocol:
    - get_descriptor() -> provider metadata
    - execute(operation, parameters, context) -> result dict
    """

    def __init__(self) -> None:
        """Initialize the provider.

        TODO: Add any setup logic (API clients, auth tokens, etc.).
        """
        self._descriptor = {class_name}Descriptor(
            operations=[
                # TODO: Define your operations here
                {class_name}OperationDescriptor(
                    operation="example_operation",
                    description="TODO: Describe what this operation does",
                    required_parameters=["input"],
                    optional_parameters=["options"],
                ),
            ],
        )
        logger.info("Initialized {display_name} connector provider")

    def get_descriptor(self) -> {class_name}Descriptor:
        """Return this provider\'s metadata descriptor."""
        return self._descriptor

    def execute(
        self,
        operation: str,
        parameters: dict[str, Any],
        context: dict[str, Any],
    ) -> dict[str, Any]:
        """Execute an operation on this provider.

        Args:
            operation: The operation name to execute.
            parameters: Operation parameters.
            context: Execution context (run_id, agent_role, etc.).

        Returns:
            Result dict with at least a \'status\' key.

        TODO: Replace the stub logic with your actual integration.
        """
        logger.info(
            "Executing %s on {provider_id}",
            operation,
            extra={{"parameters": list(parameters.keys())}},
        )

        if operation == "example_operation":
            # TODO: Implement your operation logic here
            input_data = parameters.get("input", "")
            return {{
                "status": "success",
                "result": f"Processed: {{input_data}}",
            }}

        return {{"status": "error", "error": f"Unknown operation: {{operation}}"}}
'''


def _event_handler_stub(handler_name: str, event_types: list[str]) -> str:
    """Generate an event handler stub."""
    class_name = "".join(part.capitalize() for part in handler_name.replace("-", "_").split("_"))
    event_cases = ""
    for event_type in event_types:
        event_cases += f'''
        if event_type == "{event_type}":
            # TODO: Handle {event_type} event
            logger.info("Handling {event_type}: %s", event_data.get("id", "unknown"))
            return
'''

    return f'''"""Event handler: {handler_name}.

Auto-generated by Agent-Orchestrator Studio.
Edit the TODO sections to add your event handling logic.

Register this handler with the EventBus:
    event_bus.subscribe("event_type", {class_name}Handler().handle)
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class {class_name}Handler:
    """Handles events from the orchestration engine.

    Subscribe to events via:
        event_bus.subscribe("work_item.submitted", handler.handle)
        event_bus.subscribe("phase.completed", handler.handle)
    """

    def __init__(self) -> None:
        """Initialize the handler.

        TODO: Add any setup logic (notification clients, metrics, etc.).
        """
        logger.info("Initialized {handler_name} event handler")

    def handle(self, event_type: str, event_data: dict[str, Any]) -> None:
        """Handle an event from the EventBus.

        Args:
            event_type: The type of event (e.g. 'work_item.submitted').
            event_data: Event payload.
        """
        logger.debug(
            "Received event %s with keys: %s",
            event_type,
            list(event_data.keys()),
        )
{event_cases}
        logger.warning("Unhandled event type: %s", event_type)
'''


def _hook_stub(phase_id: str, hook_name: str) -> str:
    """Generate a phase context hook stub."""
    func_name = hook_name.replace("-", "_")
    return f'''"""Phase context hook for phase '{phase_id}'.

Auto-generated by Agent-Orchestrator Studio.
Edit the TODO section to add your context injection logic.

Register in app.yaml:
    hooks:
        {phase_id}: "{func_name}:{func_name}"
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def {func_name}(context: dict[str, Any]) -> dict[str, Any]:
    """Inject additional context before phase '{phase_id}' executes.

    This hook runs before agents in the phase are invoked.  It receives
    the current phase context dict and must return the (possibly modified)
    context dict.

    Args:
        context: The current phase execution context.  Contains keys like
                 'work_item', 'phase_id', 'run_id', and any previously
                 injected data.

    Returns:
        The context dict, with any additional data added.

    TODO: Add your context injection logic below.
    """
    logger.info(
        "Running hook for phase '%s', work_item=%s",
        "{phase_id}",
        context.get("work_item", {{}}).get("id", "unknown"),
    )

    # TODO: Inject your custom context here
    # Examples:
    #   context["previous_results"] = load_previous_phase_results(context)
    #   context["external_data"] = fetch_from_api(context["work_item"])
    #   context["lookup_table"] = load_reference_data()

    return context
'''


def generate_connector_stub(
    provider_id: str,
    display_name: str,
    capability: str = "EXTERNAL_API",
) -> str:
    """Generate a connector provider Python source file.

    Args:
        provider_id: Unique provider identifier (slug).
        display_name: Human-readable provider name.
        capability: Capability type string.

    Returns:
        Python source code string.
    """
    return _connector_stub(provider_id, display_name, capability)


def generate_event_handler_stub(
    handler_name: str,
    event_types: list[str] | None = None,
) -> str:
    """Generate an event handler Python source file.

    Args:
        handler_name: Handler identifier (slug).
        event_types: Event types to handle.

    Returns:
        Python source code string.
    """
    if event_types is None:
        event_types = ["work_item.submitted", "phase.completed", "workflow.completed"]
    return _event_handler_stub(handler_name, event_types)


def generate_hook_stub(phase_id: str, hook_name: str | None = None) -> str:
    """Generate a phase context hook Python source file.

    Args:
        phase_id: Phase this hook is for.
        hook_name: Override hook function name (defaults to 'hook_{phase_id}').

    Returns:
        Python source code string.
    """
    name = hook_name or f"hook_{phase_id}"
    return _hook_stub(phase_id, name)


def generate_all_stubs(
    team: TeamSpec,
    output_dir: Path,
    *,
    force: bool = False,
) -> ExtensionStubResult:
    """Generate all extension stubs for a team profile.

    Generates:
    - Phase context hooks for phases that have agents (in extensions/hooks/).
    - A default event handler (in extensions/handlers/).

    Does NOT generate connector stubs automatically — those should be
    created on demand via the API when the user wants to integrate a
    specific service.

    Args:
        team: Team specification.
        output_dir: Profile directory to write stubs into.
        force: Override manifest ownership checks.

    Returns:
        ExtensionStubResult with generated files and write status.
    """
    result = ExtensionStubResult()
    extensions_dir = output_dir / "extensions"
    hooks_dir = extensions_dir / "hooks"
    handlers_dir = extensions_dir / "handlers"

    tracker = ManifestTracker(output_dir)

    # Phase hooks
    for phase in team.workflow.phases:
        if phase.is_terminal or not phase.agents:
            continue

        hook_name = f"hook_{phase.id}"
        relative = f"extensions/hooks/{hook_name}.py"
        code = _hook_stub(phase.id, hook_name)
        result.files[relative] = code

        file_path = output_dir / relative
        if not force:
            conflicts = tracker.check_conflicts()
            for conflict in conflicts:
                if relative in conflict:
                    result.skipped.append(relative)
                    continue

        hooks_dir.mkdir(parents=True, exist_ok=True)
        try:
            file_path.write_text(code, encoding="utf-8")
            result.written.append(file_path)
            tracker.mark_user_owned(relative)
        except OSError as exc:
            raise ExtensionStubError(
                f"Failed to write hook stub {file_path}: {exc}"
            ) from exc

    # Default event handler
    handler_code = _event_handler_stub(
        "workflow-events",
        ["work_item.submitted", "phase.completed", "workflow.completed"],
    )
    handler_relative = "extensions/handlers/workflow_events.py"
    result.files[handler_relative] = handler_code

    handler_path = output_dir / handler_relative
    handlers_dir.mkdir(parents=True, exist_ok=True)
    try:
        handler_path.write_text(handler_code, encoding="utf-8")
        result.written.append(handler_path)
        tracker.mark_user_owned(handler_relative)
    except OSError as exc:
        raise ExtensionStubError(
            f"Failed to write event handler stub: {exc}"
        ) from exc

    # Write __init__.py files for the packages
    for init_dir in [extensions_dir, hooks_dir, handlers_dir]:
        init_file = init_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text(
                f'"""Auto-generated extension package."""\n',
                encoding="utf-8",
            )

    logger.info(
        "Generated %d extension stubs (%d written, %d skipped)",
        len(result.files),
        len(result.written),
        len(result.skipped),
    )
    return result
